### ISSUE TITLE
Don't create directories unneccessarily

### ISSUE THREAD

**Issue by xrotwang** [HedvigS/Glottolog_look_up_table#2]
`requirements.R` creates a directory `./groundhog_packages` (see
https://github.com/HedvigS/Glottolog_look_up_table/blob/690a1a58ab54b984a681afabed34e6acb3113db9/requirements.R#L10 ). I think it should be left to whoever runs the code to specify this - or stick with groundhog's defaults.

**Comment by HedvigS** [comment]
I don't agree, I found some hiccups with using dir above the project folder you're in. However, for the glottolog cookbook scripts I'll avoid using groundhog altogether, at least at the start.
